users = {
    157758328: {'surname': 'Азаров',
                'name': 'Дмитрий',
                'city': 'Санкт-Петербург',
                'link': '@DeveloperAzarov',
                'exp_date': '',
                'tab_number': '119221',
                'password': '2DH64rf2',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True,
                "check_permissions": True},  # я
    876767679: {'surname': '',
                'name': '',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    963229572: {'surname': '',
                'name': '',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    475265609: {'surname': 'Палатникова',
                'name': 'Валентина',
                'city': 'Санкт-Петербург',
                'link': '@Valentina_Palatnikova',
                'exp_date': '',
                'tab_number': '124080',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    831393723: {'surname': '',
                'name': 'Ольга',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    570929460: {'surname': '',
                'name': '',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    108108080: {'surname': '',
                'name': '',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    # 948502196: {'surname': 'Невзоров', # отключился уволился? в писках нет
    #             'name': 'Владимир',
    #             'link': '',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},
    # 385253833: {'surname': '', # отключился
    #             'name': 'Наталья',
    #             'link': '',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},
    250873111: {'surname': 'Слинченко',
                'name': 'Екатерина',
                'link': '',
                'exp_date': '',
                'tab_number': '120564',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    146806250: {'surname': 'Балобан',
                'name': 'Екатерина',
                'link': '@balokatie',
                'exp_date': '',
                'tab_number': '121193',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1029474274: {'surname': 'Успенская',
                 'name': 'Екатерина',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '52848',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    # 289638600: {'surname': 'Сюник', уволилась? в списке нет
    #             'name': 'Кристина',
    #             'link': '@ChristinaSunik',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},
    1675457248: {'surname': '',
                 'name': 'Алексей',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    406430959: {'surname': '',
                'name': '',
                'link': '@fairy5555',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    963877207: {'surname': '',
                'name': 'Ксения',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    496197476: {'surname': 'Хомяк',
                'name': 'Анастасия',
                "city": "Санкт-Петербург",
                'link': '@OhNoOops',
                'exp_date': '',
                'tab_number': '122429',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    890017795: {'surname': 'Белькасми',
                'name': 'Арина',
                "city": "Санкт-Петербург",
                'link': '@arisha_belkacemi',
                'exp_date': '',
                'tab_number': '124095',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    517849162: {'surname': '',
                'name': 'Виктория',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1098186587: {'surname': '',
                 'name': 'Юрий',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    515032191: {'surname': 'Зайцева',
                'name': 'София',
                'city': 'Санкт-Петербург',
                'link': '',
                'exp_date': '30.11.2021',
                'tab_number': '122522',  # 4 окэ
                'password': 'Sophie23',
                'access': True,
                'plan_notify': True,
                'autoconfirm': False,
                'messaging': True},
    820924751: {'surname': '',
                'name': 'Елена',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Елена,-,-,
    # 890071795: {'surname': '', # отключился
    #             'name': '',
    #             'link': '',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},
    288061032: {'surname': 'Шустова',
                'name': 'Ксения',
                'link': '',
                'exp_date': '',
                'tab_number': '122576',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    925153979: {'surname': 'Васильева',
                'name': 'Ирина',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '54350',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    841821239: {'surname': 'Дзаурова',
                'name': 'Юнна',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '37636',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    727528278: {'surname': 'Айзатуллина',
                'name': 'Ильмира',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '27484',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    178343579: {'surname': '',
                'name': 'Ксения',
                'link': '@ksushalev',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    256529412: {'surname': 'Безукладников',
                'name': 'Владислав',
                'city': 'Санкт-Петербург',
                'link': '@vladdf',
                'exp_date': '',
                'tab_number': '119221',
                'password': '2DH64rf2',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': False},  # Влад,Безукладников,vladdf,
    780118341: {'surname': '',
                'name': '',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # da,son,-,
    299463905: {'surname': 'Репетилова',
                'name': 'Ольга',
                'city': 'Санкт-Петербург',
                'link': '@ol,_tlg',
                'exp_date': '31.12.22',
                'tab_number': '123892',
                'password': 'PandA177..',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    892168424: {'surname': 'Семенова',
                'name': 'Юлия',
                'city': 'Санкт-Петербург',
                'link': '@Juliaeco',
                'exp_date': '',
                'tab_number': '72266',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    378411927: {'surname': '',
                'name': 'Ксения',
                'link': '@Ksennyy',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Ксения,-,@Ksennyy,
    220666781: {'surname': 'Киселева',
                'name': 'Светлана',
                "city": "Санкт-Петербург",
                'link': '@svk2341',
                'exp_date': '',
                'tab_number': '86986',
                'password': 'VTHc5B3s96Vj24d',
                'access': True,
                'plan_notify': True,
                'autoconfirm': False,
                'messaging': True},  # Светлана,-,@stewardesssvetlana,
    868224481: {'surname': '',
                'name': 'Оксана',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Оксана,-,-,
    333113968: {'surname': 'Корнелик',
                'name': 'Мария',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Мария,Корнелик,-,
    # 613004721: {'surname': 'Верховин', # ЭТО ЛЁТЧИК!
    #             'name': 'Алексей',
    #             "city": "Санкт-Петербург",
    #             'link': '@ALEKSEI_VERHOVIN',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},  # Алексей,Верховин,@ALEKSEI_VERHOVIN,
    539234667: {'surname': '',
                'name': 'Екатерина',
                'link': '@hurican123',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Катя,-,@hurican123,
    499304227: {'surname': 'Островская',
                'name': 'Елена',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '5917',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Елена,Островская,-,
    1483057813: {'surname': '',
                 'name': 'Татьяна',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # Татьяна,-,-,
    1369111914: {'surname': '',
                 'name': 'Зайка',
                 'city': 'Санкт-Петербург',
                 'link': '@Zayka_Rinn',
                 'exp_date': '30.09.22',
                 'tab_number': '',  # 5 отделение
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'check_permissions': False,  # о сроках документов уведомлять не надо
                 'messaging': False},  # отказ от рассылки
    863993881: {'surname': '',
                'name': 'Анна',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Анна,-,-,
    875037323: {'surname': '',
                'name': 'Мария',
                'link': '@krylovasky',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Маша,-,@krylovasky,
    1211122753: {'surname': '',
                 'name': 'Анна',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # Анна,-,-,
    1137460999: {'surname': 'Малькова',
                 'name': 'Анна',
                 'city': 'Санкт-Петербург',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '5720',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # Анна,Малькова,-,
    1022939973: {'surname': 'Кайзерова',
                 'name': 'Ольга',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '',
                 'tab_number': '87991',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    858982312: {'surname': '',
                'name': 'Ольга',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Ольга,-,-,
    756293869: {'surname': 'С',  # старун, столярова, сушко?
                'name': 'Ирина',
                'link': '@x_april_x',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    571633543: {'surname': '',
                'name': 'Екатерина',
                'link': '@Ekaterina_mira1',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1222895575: {'surname': 'Аладьина',
                 'name': 'Яна',
                 'city': 'Санкт-Петербург',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '77314',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    418518645: {'surname': '',
                'name': 'Светлана',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1154590416: {'surname': 'Получанкина',
                 'name': 'Наташа',
                 "city": "Санкт-Петербург",
                 'link': '@kostnerka',
                 'exp_date': '',
                 'tab_number': '5735',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    469698535: {'surname': 'Ибрагимова',
                'name': 'Зульфия',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '120452',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    266708010: {'surname': '',
                'name': 'Яна',
                'link': '@LadyPhantom7',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    133837567: {'surname': '',
                'name': 'Елизавета',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    717725614: {'surname': 'Борисов',
                'name': 'Михаил Юрьевич',
                'city': 'Санкт-Петербург',
                'link': '',
                'exp_date': '',
                'tab_number': '110912',
                'password': 'Oscar1414',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1373324979: {'surname': '',
                 'name': 'Елена',
                 'link': '@Elenabangkok',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    321459826: {'surname': '',
                'name': '',
                'link': '@Vsu94',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    600013180: {'surname': '',
                'name': 'Alex',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Alex,-,-,
    # 714050926: {'surname': 'Абрамова',
    #             'name': 'М',
    #             'link': '',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': False,
    #             'messaging': True},  # М,Абрамова,-,
    829005443: {'surname': 'Пуйсан',
                'name': 'Светлана',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '37365',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Светлана,Пуйсан,-,
    262336534: {'surname': 'Рахманова',
                'name': 'Эльвида',
                "city": "Санкт-Петербург",
                'link': '@baeellie',
                'exp_date': '',
                'tab_number': '123893',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    703537465: {'surname': '',
                'name': 'Кирилл',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Кирилл,-,-,
    # 1639981689: {'surname': 'Bozchko',
    #              'name': 'Яна',
    #              'link': '',
    #              'exp_date': '',
    #              'tab_number': '',
    #              'password': '',
    #              'access': True,
    #              'plan_notify': True,
    #              'autoconfirm': True,
    #              'messaging': True},  # Яна,Bozchko,-,
    1893220192: {'surname': '',
                 'name': '',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # hj,-,-,
    1205064740: {'surname': 'Филиппов',
                 'name': 'Даниил',
                 'city': 'Санкт-Петербург',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '24059',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1462571647: {'surname': 'Никитенко',
                 'name': 'Светлана',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '',
                 'tab_number': '79126',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    824825350: {'surname': '',
                'name': 'Александр',
                'link': '@AviatigeR1',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    898275718: {'surname': '',
                'name': 'Леся',
                'link': '@carrotta_lesya',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    510940476: {'surname': '',
                'name': 'Ольга',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    209548076: {'surname': 'Мироняк',
                'name': 'Наталья',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '119591',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    878539570: {'surname': '',
                'name': '',
                'link': '@access_fly',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    304247011: {'surname': 'Анисимова',  # заблокировала бота
                'name': 'Анастасия',
                'city': 'Санкт-Петербург',
                'link': '',
                'exp_date': '31.07.23',
                'tab_number': '121022',
                'password': 'Nastewa4',
                'access': True,
                'plan_notify': False,
                'autoconfirm': False,
                'messaging': False},
    912694856: {'surname': '',
                'name': 'Полина',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    256030196: {'surname': '',
                'name': 'Кристина',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1723307314: {'surname': '',
                 'name': 'Анна',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # Анна,-,-,
    810938127: {'surname': '',
                'name': 'Марина',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    806890553: {'surname': '',
                'name': 'Екатерина',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    696454154: {'surname': '',
                'name': 'Снежана',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    985970603: {'surname': '',
                'name': 'Светлана',
                'link': '@burundukoks',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    933643381: {'surname': 'Анташева',
                'name': 'Анна',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '89328',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    816830262: {'surname': 'Щербина',
                'name': 'Юля',
                'city': 'Санкт-Петербург',
                'link': '@July_in_the_sky',
                'exp_date': '',
                'tab_number': '119182',  #
                'password': 'Airbus338!',  #
                'access': True,
                'plan_notify': True,
                'autoconfirm': False,
                'messaging': True},  # Юля,-,@July_in_the_sky,
    407936716: {'surname': '',
                'name': '',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # -,-,-,
    1163356557: {'surname': 'Асхадуллина',
                 'name': 'Регина Рамильевна',
                 'city': 'Москва',
                 'link': '@rega231298',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1073590803: {'surname': '',
                 'name': '',
                 'link': '@Slafen',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # Slafen,-,@Slafen,
    728146705: {'surname': 'Ковалев',
                'name': 'Евгений',
                'city': 'Москва',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Евгений,Ковалев,@Kovalevirk,
    258869319: {'surname': 'Мелешенко',
                'name': 'Лилия',
                'city': 'Санкт-Петербург',
                'link': '@qnight',
                'exp_date': '30.11.2021',
                'tab_number': '122473',
                'password': 'Sergey658',  # Sergey658
                'access': True,
                'plan_notify': False,
                'autoconfirm': False,
                'messaging': True},  # -,-,-,
    # 811248308: {'surname': 'Яшина', # уволилась? нет в списке
    #             'name': 'Наталья Алексеевна',
    #             'city': 'Санкт-Петербург',
    #             'link': '',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},
    348154674: {'surname': 'Блинова',
                'name': 'Анастасия Евгеньевна',
                'city': 'Москва',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Anastasia,Blinova,-,
    513906494: {'surname': '',
                'name': 'Кристина',
                'link': '@kbakal',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Кристина,-,@kbakal,
    202483139: {'surname': 'Кудян',
                'name': 'Света',
                "city": "Санкт-Петербург",
                'link': '@kudyaaan',
                'exp_date': '',
                'tab_number': '122450',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1848440930: {'surname': '',
                 'name': '',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # -,-,-,
    840045930: {'surname': '',
                'name': '',
                'link': '@Delaxi',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # -,-,@Delaxi,
    1185071321: {'surname': '',
                 'name': 'Наталия',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # Наталия,-,-,
    1725845730: {'surname': '',
                 'name': 'Анастасия Сергеевна',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # Анастасия Сергеевна,-,-,
    607463505: {'surname': 'Календарова',
                'name': 'Марина',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '122943',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Марина,Календарова,-,
    411098615: {'surname': 'Козьминых',
                'name': 'Юлия Александровна',
                'city': 'Москва',
                'link': '',  # Y.Volkova@rossiya-airlines.com
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Юлия,Козьминых,-,
    472586628: {'surname': '',
                'name': 'Ольга',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Ольга,-,-,   ############# До этого пользователя ушли сообщения #########
    1099137313: {'surname': '',
                 'name': 'Ольга',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True},  # Ольга,-,-,
    677476896: {'surname': '',
                'name': 'Рустам',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Рустам,-,-,
    822255437: {'surname': 'Бенина',
                'name': 'Елена',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '5795',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Елена,Бенина,-,
    1531593541: {'surname': '',
                 'name': 'Ирина',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},  # Ирина,-,-,
    557950464: {'surname': '',
                'name': 'Ростик',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Ростик,-,-,
    206635402: {'surname': '',
                'name': 'Кристина',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Кристина,-,-,
    271798618: {'surname': 'Пшеничная',
                'name': 'Алина',
                'city': 'Санкт-Петербург',
                'link': '@alinarose17',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},  # Алина,Пшеничная,@alinarose17,
    # 502881488: {'surname': '',
    #             'name': 'Кристина Андреевна',
    #             'link': '@mamimami1993inst',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},  # Кристина Андреевна,-,@mamimami1993inst,
    806082601: {'surname': '',
                'name': '',
                'link': '@skysurfer_1',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    953525245: {'surname': '',
                'name': 'Олеся',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    # 447484112: {'surname': 'Гречановский',
    #             'name': 'Константин',
    #             'link': '@MrDesperado89',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': ''}, # не работает у нас
    401096446: {'surname': 'Нестерова',
                'name': 'Наталия',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '37574',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1611742418: {'surname': '',
                 'name': 'Виктория',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    470006359: {'surname': '',
                'name': 'Надежда',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    199649584: {'surname': '',
                'name': 'Алёна',
                'link': '@Miss_Alena23',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    400983520: {'surname': 'Кузнецова',
                'name': 'Татьяна',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '87967',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1397286349: {'surname': 'Маркарян',
                 'name': 'Ольга',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '',
                 'tab_number': '5650',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1407379372: {'surname': 'Пак',
                 'name': 'Виктория',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '',
                 'tab_number': '97127',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    540494437: {'surname': '',
                'name': '',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    969980170: {'surname': '',
                'name': 'Анастасия',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    982335585: {'surname': '',
                'name': '',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    286400618: {'surname': '',
                'name': 'Макс',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    325700767: {'surname': 'Грязнова',
                'name': 'Елена',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '55604',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    874346643: {'surname': 'Романова',
                'name': 'Ольга',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '5885',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    921355860: {'surname': 'Попова',
                'name': 'Анастасия',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '78326',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1123006781: {'surname': '',
                 'name': 'Наталья',
                 'link': '@Natysia_is',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    947926034: {'surname': '',
                'name': 'Екатерина',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1738391929: {'surname': '',
                 'name': 'Анжелика',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1142489905: {'surname': '',
                 'name': '',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1745320071: {'surname': '',
                 'name': 'Илья',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1170106153: {'surname': 'Столярова',
                 'name': 'Анна',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '',
                 'tab_number': '93633',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1243276312: {'surname': '',
                 'name': '',
                 'link': '@hkfgf6',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1212201862: {'surname': '',
                 'name': '',
                 'link': '@namsk00',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    366311741: {'surname': '',
                'name': '',
                'link': '@markofi',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    534540753: {'surname': '',
                'name': 'Кристина',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    838096601: {'surname': '',
                'name': 'Михаил',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    538133044: {'surname': 'Исхакова',
                'name': 'Диана',
                'city': 'Москва',
                'link': '@ptichka_koshka',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1151464161: {'surname': '',
                 'name': 'Катерина',
                 'link': '@eka_kupr',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    # 1014066915: {'surname': 'Михайлова', нет такой ни по каким базам. может, уволилась
    #              'name': 'Лилия',
    #              'link': '',
    #              'exp_date': '',
    #              'tab_number': '',
    #              'password': '',
    #              'access': True,
    #              'plan_notify': True,
    #              'autoconfirm': True,
    #              'messaging': True},
    270687362: {'surname': 'Смирнова',
                'name': 'Анастасия',
                "city": "Санкт-Петербург",
                'link': '@smrnvanastasia',
                'exp_date': '',
                'tab_number': '95069',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    438472957: {'surname': '',
                'name': '',
                'link': '@Shepardrus',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    666627732: {'surname': 'Головнёва',
                'name': 'Наталья',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '119592',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    698762320: {'surname': '',
                'name': 'Анна',
                'link': '',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    # 710402141: {'surname': 'Филиппова', - уволилась? в списках не найдена
    #             'name': 'Анастасия Викторовна',
    #             'link': '',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},
    1004908406: {'surname': '',
                 'name': 'Светлана',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    # 284778202: {'surname': '', # отключился?
    #             'name': '',
    #             'link': '@ruslax',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},
    320971756: {'surname': '',
                'name': 'Анастасия',
                'link': '@nk8989',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    753186147: {'surname': 'Васильева',
                'name': 'Мария',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '94546',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    656954971: {'surname': 'Королёв',
                'name': 'Артём',
                "city": "Санкт-Петербург",
                'link': '@walkoffshame',
                'exp_date': '',
                'tab_number': '79666',
                'password': 'Artemka1989',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    # 772322421: {'surname': 'Печенина', # отключилась
    #             'name': 'Татьяна',
    #             'link': '',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': True,
    #             'plan_notify': True,
    #             'autoconfirm': True,
    #             'messaging': True},
    1567871581: {'surname': 'Романюк',
                 'name': 'Анна',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '29.02.24',
                 'tab_number': '5099',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    96973120: {'surname': 'Попова',  # - ?
               'name': 'Ксения',
               "city": "Санкт-Петербург",
               'link': '',
               'exp_date': '',
               'tab_number': '5810',  # -?
               'password': '',
               'access': True,
               'plan_notify': True,
               'autoconfirm': True,
               'messaging': True},
    751576676: {'surname': 'Исламова',
                'name': 'Татьяна',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '81766',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    882629903: {'surname': 'Бондарь',
                'name': 'Ольга',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '54945',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1392503861: {'surname': 'Кузьмина',
                 'name': 'Виктория',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '',
                 'tab_number': '57545',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    930074462: {'surname': 'Стахова',
                'name': 'Ольга',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '87977',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    512766466: {'surname': 'Шемякин',
                'name': 'Денис',
                'city': 'Санкт-Петербург',
                'link': '@dsemjakin',
                'exp_date': '',
                'tab_number': '122411',  #
                'password': 'Rabota5!',  #
                'access': True,
                'plan_notify': True,
                'autoconfirm': False,
                'messaging': True},
    457953731: {'surname': 'Казаков',
                'name': 'Денис',
                'city': 'Санкт-Петербург',
                'link': '@DenisAKazakov',
                'exp_date': '',
                'tab_number': '88296',
                'password': '082021Denis',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    472203318: {'surname': '',
                'name': '',
                'link': '@MessieHair',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    465898194: {'surname': 'Сараева Паршина',
                'name': 'Тоня',
                'city': 'Санкт-Петербург',
                'link': '',
                'exp_date': '',
                'tab_number': '119229',
                'password': 'Parshina15',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    562544894: {'surname': 'Чеперисова',
                'name': 'Ольга',
                'city': 'Санкт-Петербург',
                'link': '',
                'exp_date': '',
                'tab_number': '36483',
                'password': '',  # Chips-1987 - устарел
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    269793046: {'surname': 'Бекишева',
                'name': 'Мария',
                "city": "Санкт-Петербург",
                'link': '',
                'exp_date': '',
                'tab_number': '122542',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1910564254: {'surname': 'Урбан',
                 'name': 'Елена',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '',
                 'tab_number': '5800',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1459365974: {'surname': 'Богданова',
                 'name': 'Наталия',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '',
                 'tab_number': '121894',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    240176167: {'surname': 'Анищенко',
                'name': 'Александр',
                'city': 'Санкт-Петербург',
                'link': '@aleos',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'status': 'do not disturb',
                'autoconfirm': True,
                'messaging': False},
    1630023445: {'surname': 'Камлева',
                 'name': 'Эллина',
                 'city': 'Санкт-Петербург',
                 'link': '',
                 'exp_date': '31.01.24',
                 'tab_number': '5278',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'status': 'lack of info',
                 'autoconfirm': True,
                 'messaging': True},
    911748747: {'surname': 'Курай',
                'name': 'Дарья',
                'city': 'Санкт-Петербург',
                'link': '',
                'exp_date': '',
                'tab_number': '121066',
                'password': '',
                'access': True,
                'plan_notify': True,
                'status': 'lack of info',
                'autoconfirm': True,
                'messaging': True},
    1403960527: {'surname': 'Кравчук',
                 'name': 'Дария',
                 'city': 'Санкт-Петербург',
                 'link': '',
                 'exp_date': '',
                 'tab_number': '86834',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'status': 'lack of info',
                 'messaging': True},
    500246927: {'surname': 'Хуморова',
                'name': 'Наргис Мирзомудиновна',
                "city": "Санкт-Петербург",
                'link': '@nargiskhumorova',
                'exp_date': '16.11.21',  # штабной пропуск
                'tab_number': '122543',
                'password': '',
                'status': 'lack of info',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    111165022: {'surname': 'Макошин',
                'name': 'Владимир',
                'city': 'Санкт-Петербург',
                'link': '',
                'exp_date': '28.02.23',
                'tab_number': '120018',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    # 765118687: {'surname': 'Чуднов',
    #             'name': 'Илья',
    #             'link': '',
    #             'exp_date': '',
    #             'tab_number': '',
    #             'password': '',
    #             'access': 'denied'},  # RedWings
    1176934221: {'surname': 'Тополова',
                 'name': 'Катерина',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '25.12.22',
                 'tab_number': '79326',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    168825599: {'surname': 'Габисония',
                'name': 'Ксения Валерьевна',
                "city": "Санкт-Петербург",
                'link': '@kseniiich',
                'exp_date': '04.03.22',  # штабной пропуск
                'tab_number': '122967',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1641270505: {'surname': 'Лопанов',
                 'name': 'Алексей',
                 'city': 'Санкт-Петербург',
                 'link': '@kseniiich',
                 'exp_date': '',
                 'tab_number': '17962',
                 'password': 'Zx334353',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    222983592: {'surname': '',  # Виктор Гинза
                'name': 'Радмир',
                'city': 'Москва',
                'link': '@Rad_B_v',
                'exp_date': '',
                'tab_number': '',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    449958094: {'surname': 'Ободова',
                'name': 'Ксения',
                "city": "Санкт-Петербург",
                'link': '@Foxy_Snout',
                'exp_date': '31.01.24',
                'tab_number': '81006',
                'password': '',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    1075644196: {'surname': 'Овчинникова',
                 'name': 'Яна',
                 "city": "Санкт-Петербург",
                 'link': '',
                 'exp_date': '30.04.23',
                 'tab_number': '120289',
                 'password': '',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    1074227049: {'surname': 'Гогинава',
                 'name': 'Мариям',
                 "city": "Санкт-Петербург",
                 'link': '@mani_de_gogin',
                 'exp_date': '06.10.23',  # штабной
                 'tab_number': '87970',
                 'password': 'Goginava15',
                 'access': True,
                 'plan_notify': True,
                 'autoconfirm': True,
                 'messaging': True},
    265070522: {'surname': 'Гольшина',
                'name': 'Екатерина',
                'city': 'Санкт-Петербург',
                'link': '',
                'exp_date': '03.12.23',  # штабной
                'tab_number': '6179',
                'password': 'Boeing7673000821',
                'access': True,
                'plan_notify': True,
                'autoconfirm': True,
                'messaging': True},
    201090784: {'surname': 'Гайдук',
                'name': 'Дарья',
                'city': 'Санкт-Петербург',
                'link': '@qnight',
                'exp_date': '03.12.23',  # штабной
                'tab_number': '124092',
                'password': 'nAvsseav06',
                'access': True,
                'plan_notify': True,
                'autoconfirm': False,
                'messaging': True},
    82733001: {"surname": "Тутаева",  # др: 23.10.95
               "name": "Марина",
               "city": "Санкт-Петербург",  # - уточнить.. айдишку показывала
               "link": "@califren",
               "exp_date": "31.12.22",  # айдишка российская
               "tab_number": "",
               "password": "",
               "access": True,
               "plan_notify": True,
               "autoconfirm": True,
               "messaging": True},
    40570937: {"surname": "Калинина",
               "name": "Ксения",
               "city": "Санкт-Петербург",
               "link": "@KseniiaKalinina",
               "exp_date": "19.08.24",  # штабной
               "tab_number": "125451",
               "password": "",
               "access": True,
               "plan_notify": True,
               "autoconfirm": True,
               "messaging": True},
    701223454: {"surname": "Сироткина",
                "name": "Оксана",
                "city": "Санкт-Петербург",
                "link": "@Oksi_luck",
                "exp_date": "",
                "tab_number": "120725",
                "password": "Boeing118",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True},
    470446547: {"surname": "Филатова",
                "name": "Екатерина",
                "city": "Санкт-Петербург",
                "link": "@Eka_te_rinka",
                "exp_date": "",
                "tab_number": "96507",
                "password": "Dj9hpwf8.",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True},
    1165937597: {"surname": "Якушева",
                 "name": "Виктория",
                 "city": "Санкт-Петербург",
                 "link": "@",
                 "exp_date": "30.09.22",
                 "tab_number": "119168",
                 "password": "Apple12345!",
                 "access": True,
                 "plan_notify": True,
                 "autoconfirm": True,
                 "messaging": True},
    1096608481: {"surname": "Тимочкина",
                 "name": "Ольга",
                 "city": "Санкт-Петербург",
                 "link": "ссылка",
                 "exp_date": "30.04.24",
                 "tab_number": "121983",
                 "password": "",
                 "access": True,
                 "plan_notify": True,
                 "autoconfirm": True,
                 "messaging": True},
    943024308: {"surname": "Изюмская",
                "name": "Александра",
                "city": "Москва",
                "link": "",
                "exp_date": "28.01.23",  # штабной
                "tab_number": "110216",
                "password": "",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True,
                "check_permissions": True},
    796326139: {"surname": "Вишнякова",
                "name": "Мария",
                "city": "Санкт-Петербург",
                "link": "",
                "exp_date": "28.01.23",  # штабной
                "tab_number": "5999",
                "password": "",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True,
                "check_permissions": True},
    803424488: {"surname": "Мушенко",
                "name": "Анастасия",
                "city": "Санкт-Петербург",
                "link": "@lordhr",
                "exp_date": "",
                "tab_number": "87989",
                "password": "",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True,
                "check_permissions": True},
    389287909: {"surname": "Гуляева",
                "name": "Ксения",
                "city": "Санкт-Петербург",
                "link": "@ksenayy",
                "exp_date": "31.12.22",
                "tab_number": "",
                "password": "",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True,
                "check_permissions": True},
    1417017318: {"surname": "Соломко",
                 "name": "Юрий",
                 "city": "Санкт-Петербург",
                 "link": "",
                 "exp_date": "",
                 "tab_number": "54244",
                 "password": "",
                 "access": True,
                 "plan_notify": True,
                 "autoconfirm": True,
                 "messaging": True,
                 "check_permissions": True},
    355221047: {"surname": "Орищак",
                "name": "Светлана",
                "city": "",
                "link": "@s7hak",
                "exp_date": "31.12.22",
                "tab_number": "125498",
                "password": "Sveta030498",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True,
                "check_permissions": True},
    1429522051: {"surname": "Янова",
                 "name": "Татьяна",
                 "city": "Санкт-Петербург",
                 "link": "",
                 "exp_date": "30.11.22",
                 "tab_number": "88686",
                 "password": "Salasana06",
                 "access": True,
                 "plan_notify": True,
                 "autoconfirm": True,
                 "messaging": True,
                 "check_permissions": True},
    1152907987: {"surname": "Мулет Роо",
                 "name": "Александра",
                 "city": "Санкт-Петербург",
                 "link": "",
                 "exp_date": "30.11.23",
                 "tab_number": "5662",
                 "password": "",
                 "access": True,
                 "plan_notify": True,
                 "autoconfirm": True,
                 "messaging": True,
                 "check_permissions": True},
    183343884: {"surname": "Меденцова",
                "name": "Мария",
                "city": "Санкт-Петербург",
                "link": "",
                "exp_date": "",
                "tab_number": "87972",
                "password": "",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True,
                "check_permissions": True},
    499326333: {"surname": "Петрова",
                "name": "Дарья",
                "city": "",
                "link": "",
                "exp_date": "31.12.22",
                "tab_number": "",
                "password": "",
                "access": True,
                "plan_notify": True,
                "autoconfirm": True,
                "messaging": True,
                "check_permissions": True},
}
